server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/busservice
    username: postgres
    password: 8500

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  config:
    import: optional:configserver:http://localhost:9090


  application:
    name: BUS-SERVICE

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
